SRC_F				=	init_parsing \
						lexer_utils \
						token_utils \
						token_is \
						parse_line \
						ctx_init \
						ctx_clear \
						ctx_error \
						ctx_error_exit \
						ctx_exit \
						command_execute \
						command_parse \
						command_add \
						command_new \
						command_free \
						command_redirections \
						debug_utils \
						builtins_try \
						bin_find \
						bin_find_path \
						env_find \
						env_find_bin \
						free_2d_array \
						pipeline \
						pipeline_free \
						pipeline_new \
						pipeline_add \
						pipeline_parse \
						pipeline_wait \
						pipeline_utils \
						pipeline_execute \
						signals \
						main
