SRC_F				=	free/free \
						free/free_env \
						init/init_ctx \
						init/init_parse \
						lexer/lexer_read \
						lexer/lexer_token \
						lexer/lexer_utils \
						lexer/lexer_token_is \
						parser/parser_command \
						parser/parser_pipeline \
						parser/parser_utils \
						ctx_init \
						ctx_clear \
						ctx_error \
						ctx_error_exit \
						ctx_exit \
						command_execute \
						command_parse \
						command_add \
						command_new \
						command_free \
						command_redirections \
						command_bin \
						debug_utils \
						builtins_try \
						bin_find \
						bin_find_path \
						env_find \
						env_find_bin \
						free_2d_array \
						signals \
						exec_cmdas \
						exec_cmda_child \
						exec_cmdas_get_fds \
						pipes_utils \
						main
