SRC_F				= \
						builtins/builtins_try \
						builtins/builtins_try_utils \
						builtins/builtins_try_utils2 \
						builtins/builtins_redirect \
						builtins/builtins_redirect_utils \
						builtins/builtin_echo \
						builtins/builtin_cd \
						builtins/builtin_cd_utils \
						builtins/builtin_pwd \
						builtins/builtin_export \
						builtins/builtin_export_utils \
						builtins/builtin_export_utils2 \
						builtins/builtin_unset \
						builtins/builtin_env \
						builtins/builtin_exit \
						builtins/builtin_pipeline \
						checker/token_checker \
						checker/token_checker_utils \
						command/command_parse \
						command/command_parse_utils \
						command/command_parse_utils2 \
						command/command_add \
						command/command_new \
						command/command_bin \
						command/command_execute \
						command/command_execute_utils \
						env/env \
						env/env_utils \
						env/env_find \
						env/env_find_bin \
						env/env_quotes \
						env/env_quotes_utils \
						error/error \
						error/ctx_error_exit \
						error/error_utils \
						error/error_utils2 \
						exec/execute_pipeline \
						exec/execute_single_command \
						exec/execute_single_command_child \
						exec/execute_single_command_env_array \
						exec/execute_redirection \
						exec/execute_redirection_utils \
						exec/execute_pipeline_builtin \
						exec/execute_pipeline_command \
						exec/execute_pipeline_setup \
						exec/execute_pipeline_utils \
						exec/execute_pipeline_utils2 \
						exec/execute_pipeline_process_command \
						free/free_env \
						free/free_2d_array \
						free/free_ctx \
						free/free_command \
						init/init_ctx \
						init/init_parse \
						lexer/lexer_read \
						lexer/lexer_read_utils \
						lexer/lexer_read_utils2 \
						lexer/lexer_token \
						lexer/lexer_tokenize \
						lexer/lexer_token_utils \
						lexer/lexer_utils \
						lexer/lexer_token_is \
						memory/memory \
						memory/cleanup_utils \
						path/bin_find \
						path/bin_find_utils \
						path/bin_find_path \
						path/path_error \
						redir/heredoc \
						redir/heredoc_expand \
						redir/heredoc_expand_utils \
						redir/heredoc_process \
						redir/heredoc_signals \
						redir/heredoc_utils \
						redir/heredoc_utils2 \
						redir/redir_cleanup \
						signals/signals \
						validation/validation \
						main_utils \
						main_utils2 \
						main
TSRC_F			=		$(subst main,test/main,$(SRC_F))
